### ISSUE TITLE
build: github.com/cloudy-sky-software/pulumi-provider-framework not public

### ISSUE THREAD

**Issue by oncilla** [cloudy-sky-software/pulumi-tailscale-native#107]
Hi there,

I'm interested in using this plugin. Unfortunately, it seems that github.com/cloudy-sky-software/pulumi-provider-framework is not public and can thus this plugin can not be built.
Is this by design, or an oversight?

**Comment by praneetloke** [comment]
@oncilla yeah `pulumi-provider-framework` is not public at the moment and so this provider cannot be built from source. You can, however, use/download the provider binaries available in GitHub [Releases](https://github.com/cloudy-sky-software/pulumi-tailscale-native/releases).

**Comment by oncilla** [comment]
Alright. Thank you for the clarification 👍

**Comment by praneetloke** [comment]
@oncilla all the SDKs are published to their respective package manager repos so you should be able to simply install the respective SDK and the plugin binary will automatically be installed for you.
